### ISSUE TITLE
How to delete/replace a model

### ISSUE THREAD

**Issue by EVAUTOAI** [postgresml/postgresml#1032]
Once trained, all models seem to be there. How do we train while replacing any existing model with that name (or) just delete a model

**Comment by levkk** [comment]
Take a look at `pgml.deploy`: https://postgresml.org/docs/guides/predictions/deployments. We currently don't support deleting models with an API, but you can just delete it from `pgml.models` table with `DELETE FROM ...`

**Comment by montanalow** [comment]
You'll also want to delete the associated `pgml.files`, which store the actual model data. We should expose an api for this.

**Comment by EVAUTOAI** [comment]
Thanks! I am deleting from pgml.files, pgml.models and pgml.projects -- hope this would do
