### ISSUE TITLE
Unable to create classification models

### ISSUE THREAD

**Issue by EVAUTOAI** [postgresml/postgresml#1035]
I am trying to build a classification model on iris dataset below is its description (column class2 is just a copy of the class column):
<img width="628" alt="image" src="https://github.com/postgresml/postgresml/assets/97277014/4988a1a1-1c99-4351-a3be-4a419e1ad733">
I am getting the below error:
<img width="1309" alt="image" src="https://github.com/postgresml/postgresml/assets/97277014/78789b7d-3df3-4862-b4ce-8c7e6f691e29">

**Comment by montanalow** [comment]
This is a dup of #1007. You'll need to update to update to master where this assertion has been converted to a more helpful error message.

**Comment by EVAUTOAI** [comment]
Ok, can you please help me understand how to do that?
