### ISSUE TITLE
[SDK] Add character limit to chunks

### ISSUE THREAD

**Issue by levkk** [postgresml/postgresml#1076]
We should limit the size of inputs passed to `pgml.embed()` and `pgml.transform()` as to avoid overly large inputs. We need to ensure that the chunker produced parts that are not too large and not too small. If we allow large amounts of text to be sent in one call, the call has a higher probability of failure.

**Comment by montanalow** [comment]
I think this is an application issue, not something we can reasonably control at the extension level.
