### ISSUE TITLE
I think we should move toward our client side syntax highlighting for all code to have a single consistent presentation.

### ISSUE THREAD

**Issue by chillenberger** [postgresml/postgresml#1150]
I think we should move toward our client side syntax highlighting for all code to have a single consistent presentation.

_Originally posted by @montanalow in https://github.com/postgresml/postgresml/issues/1149#issuecomment-1801226503_

**Comment by montanalow** [comment]
@chillenberger I believe you've taken this up.

**Comment by chillenberger** [comment]
Yep working on it now.
