### ISSUE TITLE
Randomly slow pgml.embed due to model being loaded per db connection / per process id (pg_backend_pid)

### ISSUE THREAD

**Issue by mhoshi-vm** [postgresml/postgresml#1175]
I have been playing with a standard spring application (which uses HikariCP as JDBC connection pool manager ) and been creating embeddings with standard `pgml.embed`.
However I have been encountering random slowness with my app. I have added the following code for testing purpose.

```
   @Transactional
    public List<Summary> get(String prompt, Integer limit) {
        SummaryMapper recordMapper = new SummaryMapper();

        List<Map<String, Object>> rows = this.jdbcTemplate.queryForList("select * from pg_backend_pid()");


        System.out.println("Start time : " + LocalDateTime.now());

        for (Map<String, Object> row : rows) {
            System.out.println("PG Backend PID : " + row.get("pg_backend_pid"));
        }

        List<Summary> summaries = this.jdbcTemplate.query(
                "SELECT id, session_id, title, content, pgml.embed(?, ?)::vector <-> embeddings AS distance FROM summary ORDER BY distance LIMIT ?",
                recordMapper, this.embeddingModels, prompt, limit);

        System.out.println("End time : "+ LocalDateTime.now());

        return summaries;
    }
 ```
 
Here is the result of the above code. If you look at the `pg_backend_pid` ...
- The very first call with 161158, is taking 16 seconds 
- The remaining requests with 161158 is executed within 1 second
- The very last call the pid, changes to 161468, and again I see a 16 second delay

```
Start time : 2023-11-20T15:03:31.324552
PG Backend PID : 161158
End time : 2023-11-20T15:03:46.101962
Start time : 2023-11-20T15:03:56.740049
PG Backend PID : 161158
End time : 2023-11-20T15:03:57.320734
Start time : 2023-11-20T15:03:58.431421
PG Backend PID : 161158
End time : 2023-11-20T15:03:58.992843
Start time : 2023-11-20T15:04:00.050671
PG Backend PID : 161158
End time : 2023-11-20T15:04:00.577102
Start time : 2023-11-20T15:07:12.321284
PG Backend PID : 161158
End time : 2023-11-20T15:07:13.349704
Start time : 2023-11-20T15:11:04.803518
PG Backend PID : 161158
End time : 2023-11-20T15:11:05.616185
Start time : 2023-11-20T15:18:38.631531
PG Backend PID : 161158
End time : 2023-11-20T15:18:39.331488
Start time : 2023-11-20T15:22:43.661159
PG Backend PID : 161158
End time : 2023-11-20T15:22:44.358151
Start time : 2023-11-20T15:26:34.033064
PG Backend PID : 161158
End time : 2023-11-20T15:26:34.952128
Start time : 2023-11-20T15:35:15.277025
PG Backend PID : 161468
End time : 2023-11-20T15:35:32.536161
```

Per my colleages review, it seems the embedding model is loaded per process id (which in this case seems to be every db connection)
I have seen that (although un-ideal) adding following parameter , which only creates 1 connection and does not close the connection infinitely, at least mitigates the slowness.

```
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.idle-timeout=0
spring.datasource.hikari.maxLifetime=0
```

Overall, it seems inefficient that the model is being loaded on memory on all db connections. Is there any plan to share the model between connections ?

**Comment by montanalow** [comment]
Yep, it's inefficient to frequently open/close connections to Postgres, _in general_. This is why we created [PgCat](https://github.com/postgresml/pgcat). You should be able to configure your connections to be as long lived as you need, and shared across clients by the pooler. Additionally, this gives you a clean horizontal scale out strategy across multiple replicas if you need.
