### ISSUE TITLE
"one, two, three" example on website is missing FROM clause

### ISSUE THREAD

**Issue by joelonsql** [postgresml/postgresml#1215]
The query below at the [https://postgresml.org/](https://postgresml.org/) front page is missing the `FROM` and doesn't work.

```
SELECT pgml.predict(
  'Sales Forecasting',
  ARRAY[
    last_week_sales,
    week_of_year
  ]
) AS prediction
ORDER BY prediction DESC
```

I think it should be:

```
SELECT pgml.predict(
  'Sales Forecasting',
  ARRAY[
    last_week_sales,
    week_of_year
  ]
) AS prediction
FROM hist_sales
ORDER BY prediction DESC
```

...since `hist_sales` is the `relation_name` in the `pgml.train` command, or maybe some other like `current_sales`, but no table at all seems confusing.

**Comment by montanalow** [comment]
Good catch. We'll get this fixed.
