### ISSUE TITLE
 Defects of deploy mechanism

### ISSUE THREAD

**Issue by frg01** [postgresml/postgresml#1259]
Defects of the deployment mechanism. I trained four times and did not deploy automatically. 
Assume that my fourth model has the highest score, but its predict cannot be used. 

At this time, I use deploy to deploy. There are three ways to deploy, most_recent, best_score, and rollback. most_recent will deploy the fourth model, best_score will also deploy the fourth model, and rollback will not work. So this project is an invalid project, right? 

I can only delete my project, there is no other way.

-- just change xgboost 、xgboost_random_forest 、lightgbm、catboost
select from pgml.train(
    project_name => 'Diabetes Regression',
    task => 'regression',
    relation_name => 'pgml.diabetes',
    y_column_name => 'target',
    algorithm=> 'ada_boost'
);

SELECT from pgml.deploy(
    project_name => 'Diabetes Regression',
    strategy => 'best_score'
);

SELECT from pgml.deploy(
    project_name => 'Diabetes Regression',
    strategy => 'best_score'
);

**Comment by montanalow** [comment]
Starting with a fresh install on master, I'm able to train and deploy with ada_boost/xgboost/lightbgm and deploy models.

What version are you on, and what's in your models table for this project?

```
pgml=# select * from pgml.models join pgml.projects on projects.id = models.project_id and projects.name = 'Diabetes Regression';
```

**Comment by montanalow** [comment]
Ah, I see, you're creating a hypothetical. We handle that hypothetical case. Rollback is restricted to models other than the currently deployed one.

https://github.com/postgresml/postgresml/blob/master/pgml-extension/src/api.rs#L356-L362

**Comment by frg01** [comment]
> We handle that hypothetical case. Rollback is restricted to models other than the currently deployed one.
> 
> https://github.com/postgresml/postgresml/blob/master/pgml-extension/src/api.rs#L356-L362
> 
> Feel free to re-open if I've missed what you're getting at, or you have a test case that illustrates misbehavior. The code you've listed runs for me.

So is the description of rollback in pgml's official documentation not updated or not comprehensive enough?
https://postgresml.org/docs/introduction/apis/sql-extensions/pgml.deploy
”“”
rollback	The model that was last deployed for this project is immediately redeployed, overriding the currently deployed model.
“”“
***The description here means that rollback will deploy the most recently deployed model, but my four trains are not automatically deployed. How to use rollback?

**Comment by montanalow** [comment]
Our docs are also open source, so you can contribute something that makes the behavior more clear. 

https://github.com/postgresml/postgresml/blob/master/pgml-cms/docs/introduction/apis/sql-extensions/pgml.deploy.md?plain=1#L87

1) It's not clear to me why any of your training runs were not deployed previously. 
2) It's not clear to me why you'd want to rollback if nothing has been deployed.
3) Suppose a "prediction fails"... what does that mean specifically? Do you mean a bug in PostgresML, or a model that has poor performance in some case. If this is the case, a rollback should work, if you had a previously successful model. Otherwise, we'll need a bug report/patch/fix outside of a rollback cycle.
4) Specifying a model.id to deploy seems like a nice enhancement. PRs welcome.

**Comment by frg01** [comment]
> Our docs are also open source, so you can contribute something that makes the behavior more clear.
> 
> https://github.com/postgresml/postgresml/blob/master/pgml-cms/docs/introduction/apis/sql-extensions/pgml.deploy.md?plain=1#L87
> 
> 1. It's not clear to me why any of your training runs were not deployed previously.
> 2. It's not clear to me why you'd want to rollback if nothing has been deployed.
> 3. Suppose a "prediction fails"... what does that mean specifically? Do you mean a bug in PostgresML, or a model that has poor performance in some case. If this is the case, a rollback should work, if you had a previously successful model. Otherwise, we'll need a bug report/patch/fix outside of a rollback cycle.
> 4. Specifying a model.id to deploy seems like a nice enhancement. PRs welcome.

If I could use model.id for deployment, then the bugs in my hypothetical testing strategy would be solved.


I will clearly explain my hypothesis here, subject to several conditions: 
1. Bugs may occur anywhere. 
3. Do not use automatic deployment during train. 
3. During the four training sessions, the last train has the highest score.
4. This highest score, which is the fourth model, can train successfully, but predict cannot. (This is an assumption, it could happen)

Based on the above 4 conditions. 
We found that after manually executing deploy, we could not use this project. The specific reasons are as follows: 
1. best_score will only deploy the fourth highest-scoring model, but it cannot predict. 
3. most_recent can only deploy the fourth model, because it is the model after the most recent training. 
4. 3. Rollback can only deploy models that have been deployed. I did not use automatic deployment during train, that is, none of the four models were deployed.
Now, we can say that this project cannot be used and has to be deleted, because we can only deploy a fourth model that cannot be predicted

thanks lot for your reply！
