### ISSUE TITLE
Documentation never states the extension name

### ISSUE THREAD

**Issue by tate-button** [postgresml/postgresml#1306]
Considering PostgresML is an extension, why doesn't the Installation section of the specify the exact name of the extension to be installed.

**Comment by montanalow** [comment]
Internally, we've started to refer to the extension more as `pgml`, as opposed to the entire platform as PostgresML. This is outlined in [the overview](https://postgresml.org/docs/), and `pgml` shows up frequently in our code samples, e.g. all functions are namespaced to the extensions schema.

Our docs are also open source, so feel free to suggest additional clarification points where you think it'd be useful context.

**Comment by tate-button** [comment]
> Internally, we've started to refer to the extension more as `pgml`, as opposed to the entire platform as PostgresML. This is outlined in [the overview](https://postgresml.org/docs/), and `pgml` shows up frequently in our code samples, e.g. all functions are namespaced to the extensions schema.
> 
> Our docs are also open source, so feel free to suggest additional clarification points where you think it'd be useful context.

Thanks so much! My boss posted this from my github- I'm not at all qualified to comment on anyone else's code, or documentation.
