### ISSUE TITLE
Input data structure and recursion error

### ISSUE THREAD

**Issue by tylerdavis** [postgresml/postgresml#133]
First of all, I would like to preface that I have absolutely no experience, so my apologies in advance for the naivete.

I am seeing an error when attempting to train a model:

```
Query 1 ERROR: ERROR:  RecursionError: maximum recursion depth exceeded in comparison
CONTEXT:  Traceback (most recent call last):
  PL/Python function "train", line 4, in <module>
    status = train(
  PL/Python function "train", line 794, in train
  PL/Python function "train", line 650, in fit
  PL/Python function "train", line 363, in data
  PL/Python function "train", line 32, in flatten
  PL/Python function "train", line 33, in flatten
  PL/Python function "train", line 33, in flatten
  PL/Python function "train", line 33, in flatten
  PL/Python function "train", line 33, in flatten
  PL/Python function "train", line 33, in flatten
  PL/Python function "train", line 33, in flatten
```

## Data

My database view returns two columns

```
"{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...}",1
```

Where the vector is an `Integer[]` column comprised of 1200 values and `result` is an integer.

I am seeing the error when I call the following:

```
SELECT * FROM pgml.train(
  'Project - category:build',
  'classification',
  'category_build',
  'result'
)
```

Am I structuring my data incorrectly? Can I use an integer array to provide the training data?

Thank you very much for your patience and assistance!

**Comment by montanalow** [comment]
Thanks for the report. I've released 0.9.1 with a fix. Our test case did not include an array large enough to catch excessive recursive calls. Your example should work with the new version.
