### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like google-t5/t5-base is not the path to a

### ISSUE THREAD

**Issue by zabzd999** [postgresml/postgresml#1409]
![image](https://github.com/postgresml/postgresml/assets/6244724/029de13a-d5e5-4b9c-8ec1-044c04926f7f)

![image](https://github.com/postgresml/postgresml/assets/6244724/418f55d4-f466-48c7-9972-9d242d6aec2d)

**Comment by montanalow** [comment]
google redirect is unrelated.

**Comment by kczimm** [comment]
@zabzd999 can you please provide the output of the following:

```SQL
SELECT * FROM pgml.version();
```

and 

```SQL
SELECT * FROM pgml.python_pip_freeze();
```

**Comment by zabzd999** [comment]
![image](https://github.com/postgresml/postgresml/assets/6244724/b0ad5944-779a-46d6-92d0-81185b866313)
![image](https://github.com/postgresml/postgresml/assets/6244724/220b11be-aefd-4c8b-a97a-a943bd55eaf3)
Because my network can't access huggingface.co. I've made the docker container accessible to huggingface.co via a web proxy. But why can't the postgresml python code access huggingface.co?

**Comment by zabzd999** [comment]
Who can tell me how to make the Python code in Postgresml accessible to huggingface.co through HTTP proxy

**Comment by kczimm** [comment]
Can you access Huggingface from the container via any means? or are you finding that it's only the Python code in PostgresML that cannot access Huggingface using your HTTP proxy inside of the container?

**Comment by zabzd999** [comment]
I configure the https_proxy in the hf_api.py code of PostgresML.    It works well.
