### ISSUE TITLE
Unable to add new project

### ISSUE THREAD

**Issue by AshnaSabu123** [postgresml/postgresml#151]
While trying to add new project we are getting 403 error. Please find the below screenshot.

![image](https://user-images.githubusercontent.com/97601313/169217510-e0331337-65bc-4eae-8655-cb518bd539fe.png)

And also we have made changes in allowed hosts entry in the following files which is under the directory pgml_dashboard .env.TEMPLATE, .env.docker and  settings.py . Please let us know whether these changes are possible or not.

**Comment by AshnaSabu123** [comment]
I have hosted postgreml in our custom URL and was required to add our URL as  ALLOWED_HOST in the above files, I guess this modification lead to this 403 error, since the localhost URL implementation is wokring fine.

**Comment by montanalow** [comment]
You will need to copy .env.TEMPLATE to .env for it to be used, or else export those variables into the shell environment. I’ll try to add some clarifications to the documentation.
