### ISSUE TITLE
ERROR: Service 'postgres' failed to build: Unknown flag: chown

### ISSUE THREAD

**Issue by sdelobel** [postgresml/postgresml#154]
Hi,
After clone repo, I've an error during docker-compose

# cd postgresml && docker-compose up
Building postgres
Step 1/14 : FROM debian:bullseye-slim
 ---> c9cb6c086ef7
Step 2/14 : MAINTAINER docker@postgresml.com
 ---> Using cache
 ---> 3664ba4873e1
Step 3/14 : RUN apt-get update
 ---> Using cache
 ---> d923784e5c89
Step 4/14 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> daef8f796ade
Step 5/14 : ENV TZ Etc/UTC
 ---> Using cache
 ---> 3af4c9b887c7
Step 6/14 : RUN apt-get install -y postgresql-plpython3-13 python3 python3-pip postgresql-13 tzdata sudo cmake
 ---> Using cache
 ---> 2e573258b766
Step 7/14 : RUN pip3 install xgboost sklearn diptest
 ---> Using cache
 ---> 3f93c7617c69
Step 8/14 : COPY --chown=postgres:postgres . /app
ERROR: Service 'postgres' failed to build: Unknown flag: chown

My version of docker in my centos
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by levkk** [comment]
Your docker version seems to be extremely old (I think it reached EOL in 2017). Please upgrade to something more recent, preferably version 20.
