### ISSUE TITLE
Problems with "Quick Start with Docker" instructions

### ISSUE THREAD

**Issue by dwwinters** [postgresml/postgresml#1593]
I am encountering several problems while going through the [Quick Start with Docker instructions](https://postgresml.org/docs/open-source/pgml/developers/quick-start-with-docker) from the documentation. I've tried them with Docker Desktop on both Mac M1 and Windows machines and am not able to reproduce the results from the instructions.

Here are the issues I've encountered:
1. Dashboard is not accessible at localhost:8000 ("localhost didn’t send any data") when the container is running
2. Running the provided `docker run` command does result with a psql prompt, but includes an error message ("sudo: handle_sigchld_pty: waitpid: No child processes")
3. Running the example Embeddings command returns this error: `ValueError: Loading Alibaba-NLP/gte-base-en-v1.5 requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.`
4. Under "Training an XGBoost Model," the trained model has much worse metrics that what is shown in the instructions: `{"f1": NaN, "precision": 0.1, "recall": NaN, "accuracy": 0.100222714, "mcc": NaN, "fit_time": 0.035050604, "score_time": 0.00171086}`
5. And obviously the predictions from this model do not match what is shown in the instructions.

It would be helpful if the instructions were updated with corrections and/or clarifications. Perhaps there are missing steps that can be documented? Or maybe they are not aligned with the latest published docker image?

**Comment by oliviernabuio** [comment]
To fix the third issue:
```
SELECT pgml.embed(
    'Alibaba-NLP/gte-base-en-v1.5',
    'passage: PostgresML is so easy!', '{"trust_remote_code": true}'::JSONB
);
```
Related doc that I found since I had the same issue:
https://postgresml.org/docs/open-source/pgml/api/pgml.embed

**Comment by dwwinters** [comment]
Thanks @oliviernabuio, I had figured out the same on Sunday. But thanks for confirming, because I also noticed the embedding doesn't match the results in the documentation.

**Comment by dwwinters** [comment]
I'm going to close this issue and open new ones for each of the remaining issues. I think 4 & 5 are probably just the documentation needing to be updated. For the first issue with the dashboard, I think that could be an actual bug in the code or the container. When I `docker exec` into the container, the `pgml-dashboard` process has a status of `defunct`.
