### ISSUE TITLE
Docker: pgml-dashboard not starting

### ISSUE THREAD

**Issue by HOZHENWAI** [postgresml/postgresml#1595]
Following the issues described in [the issue 1593](https://github.com/postgresml/postgresml/issues/1593).
Following the instructing in the docker-quickstart, the pgml-dashboard is not running.
Issues looks to be a missing variable:
`SITE_SEARCH_DATABASE_URL`
modifying the `dashboard.sh` by adding:
`export SITE_SEARCH_DATABASE_URL=postgres://postgresml:postgresml@127.0.0.1:5432/postgresml` will do the trick.

**Comment by dwwinters** [comment]
I had to make this same change to get the dashboard running locally. Glad to hear that this fix also works for the Docker image.

**Comment by montanalow** [comment]
@SilasMarvin  We may need to copy `.env.development` to `.env` as part of the docker build.

**Comment by SilasMarvin** [comment]
> @SilasMarvin We may need to copy `.env.development` to `.env` as part of the docker build.

This should be an easy fix. Need to add it here: https://github.com/postgresml/postgresml/blob/fd1e3f87633f863b210ea28bed9e1ecc6f3deae4/docker/dashboard.sh#L4

I can get this fixed today.

**Comment by SilasMarvin** [comment]
Tested locally this is working now: https://github.com/postgresml/postgresml/pull/1597
