### ISSUE TITLE
Cannot access gated repo for url

### ISSUE THREAD

**Issue by chmoder** [postgresml/postgresml#1617]
How do we access "gated" huggingface repos with [pgml](https://pypi.org/project/pgml/)?  I am using https://postgresml.org/docs/open-source/pgml/developers/quick-start-with-docker setup.  I also tried adding an environment variable like so:

```SHELL
docker run \
    -it \
    -v postgresml_data:/var/lib/postgresql \
    -p 5433:5432 \
    -p 8000:8000 \
    -e HF_TOKEN='!!!MY_HF_TOKEN!!!' \
    ghcr.io/postgresml/postgresml:2.9.3 \
    sudo -u postgresml psql -d postgresml
```

```
Exception: error returned from database: Traceback (most recent call last):
  File "transformers.py", line 489, in transform
  File "transformers.py", line 458, in create_pipeline
  File "transformers.py", line 315, in __init__
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 416, in cached_file
    raise EnvironmentError(
 OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
401 Client Error. (Request ID: Root=1-66d4b149-5327d5d473937f2a155bff0e;89e4b468-ec1e-42bf-acc9-d99c3acd74c0)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must be authenticated to access it.
```

**Comment by chmoder** [comment]
I was able to verify that the issue is the missing token by editing `/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/utils/hub.py` and hard coding the `token` variable to my hugging face access token.

**Comment by skrenek** [comment]
It's not a permanent fix for your issue, but another workaround may be running this query in your database session before you run any of the pgml functions:
`SELECT set_config('pgml.hf_token', 'hf_your_token_value', false);`

**Comment by cwbeck** [comment]
I can't find a work around for this. Is this project still in active development? Seems 2.9.3 is still the latest version.

**Comment by montanalow** [comment]
Passing a HuggingFace `token` is documented in the examples here:

https://github.com/postgresml/postgresml/blob/master/pgml-extension/examples/transformers.sql#L15

We also maintain backward compatibility with the old huggingface `use_auth_token` documented in the code:

https://github.com/postgresml/postgresml/blob/master/pgml-extension/src/bindings/transformers/transformers.py#L266
