### ISSUE TITLE
cannot build custom docker image with python3.10

### ISSUE THREAD

**Issue by zebehringer** [postgresml/postgresml#1635]
We have a custom image based on the official postgres image, which is based on debian:bookworm.
We cannot install python3.10 from unstable, nor from deadsnakes. It seems that it has been removed from unstable, and I don't see it in deadsnakes for ubuntu:jammy, so I'm unsure as to how you guys are still able to build your image.
I can build the image with installing python3.11, but when starting it up, `libpython3.10.so.1` (or whatever it is) seems to still be required at runtime by the pgml extension.

What is the plan for upgrading from python3.10 to 3.11 or higher?
Along the same lines, do you plan to build the pgml extension package for ubuntu:noble?

**Comment by zebehringer** [comment]
I now see https://github.com/postgresml/postgresml/issues/1242 and understand better, so I'm now just wondering how soon you'll have a build for noble, assuming python 3.11 or 3.12 is the default for noble and would be linked

In the meantime, we'll see about building from source on debian

**Comment by montanalow** [comment]
We have separated requirements.txt into python 3.12 for more recent distros

https://github.com/postgresml/postgresml/blob/master/pgml-extension/requirements.py312.txt

**Comment by gaspardc-met** [comment]
Hi @zebehringer ,
Sorry to sidetrack the conversation, but how exactly do you build a custom image based on bookworm ? 
Do you build pgml and pgml-dashboard from source or from https://apt.postgresml.org ?

**Comment by zebehringer** [comment]
Hi @gaspardc-met we first have a docker "builder" running ubuntu, where we install the pgml package as download only. Then in the docker "runner" running bookworm we copy the package over and do some transformation with zstd and some other tools so that it can be installed on debian. It has worked fine for over a year, but upgrading has been a chore every time we have to.
I'm currently trying to build pgml from source for debian using `rust:bookworm` as the builder (but I'm having issues at the `cargo pgrx package` step). This would be a lot less of a hack if I can get it working. I'm not sure which version of rust is used in the pgml actions runner, so I'm just guessing, and currently trying rust 1.79. I'm also hoping that upgrading my mac just now to Sequoia 15.0.1 will help per this thread https://github.com/pgcentralfoundation/pgrx/issues/1614 🤞

**Comment by gaspardc-met** [comment]
Thanks for the details.
I tried very naively to build a lightweight image without cuda and it failed on the pgml install from their repo: https://github.com/postgresml/postgresml/issues/1638

How did you move past this ?

**Comment by zebehringer** [comment]
I finally got it working building pgml from source in a rust builder container and then running in the official postgres 15 or 16 bookwork image, with python3.11. As far as I know this does not use cuda (@gaspardc-met)

```
FROM rust:1.79-bookworm AS builder

ARG CACHEBUST=1
ARG PGVERSION=16
ARG PGML_VERSION=2.9.3
ARG DEBIAN_FRONTEND=noninteractive
ARG TARGETARCH
ENV TZ=Etc/UTC
ENV PYTHON_VERSION=3.11

WORKDIR /app

RUN apt update && apt-get install -y git lsb-release gpg

RUN git clone --depth 1 --branch v${PGML_VERSION} https://github.com/postgresml/postgresml.git && \
    cd postgresml && \
    git submodule update --init --recursive

# PostgreSQL apt
RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update && apt-get install -y \
    dpkg \
    libpython${PYTHON_VERSION}-dev python${PYTHON_VERSION}-dev \
    postgresql-${PGVERSION} postgresql-server-dev-${PGVERSION} \
    gettext \
    libopenblas-dev \
    libssl-dev \
    bison \
    flex \
    pkg-config \
    libreadline-dev \
    libz-dev \
    tzdata \
    cmake \
    libpq-dev \
    libclang-dev \
    lld

WORKDIR /app/postgresml/pgml-extension

RUN cargo install cargo-pgrx --version "0.11.3" --locked && \
    cargo pgrx init --pg${PGVERSION}=/usr/lib/postgresql/${PGVERSION}/bin/pg_config && \
    cargo pgrx package --pg-config /usr/lib/postgresql/${PGVERSION}/bin/pg_config

ARG RELEASE_DIR="target/release/pgml-pg${PGVERSION}"
ARG PACKAGE_VERSION="${PGML_VERSION}"
ARG ARCH="${TARGETARCH}"
RUN mkdir -p "${RELEASE_DIR}/DEBIAN" && \
    (cat ../packages/postgresql-pgml/DEBIAN/control | envsubst '${PGVERSION} ${PACKAGE_VERSION} ${ARCH}') > "${RELEASE_DIR}/DEBIAN/control" && \
    dpkg-deb \
    --root-owner-group \
    -z1 \
    --build "${RELEASE_DIR}" \
    "../../pgml.deb"

FROM postgres:16-bookworm AS runner

ARG CACHEBUST=1
ARG DEBIAN_FRONTEND=noninteractive
ARG TARGETARCH
ARG PGVERSION=16
ENV TZ=Etc/UTC

COPY --from=builder --chown=postgres:postgres /app/postgresml/pgml-extension/requirements.macos.txt /app/requirements.arm64.txt
COPY --from=builder --chown=postgres:postgres /app/postgresml/pgml-extension/requirements.linux.txt /app/requirements.amd64.txt
COPY --from=builder --chown=postgres:postgres /app/pgml.deb /app/pgml.deb

WORKDIR /app

RUN apt-get update && apt-get install -y \
    tzdata \
    python3.11-dev \
    python3-pip \
    postgresql-${PGVERSION}-pgvector && \
    pip3 install --break-system-packages -r "requirements.${TARGETARCH}.txt" && \
    rm requirements.*.txt &&\
    apt-get install -y /app/pgml.deb && rm /app/pgml.deb && \
    mkdir -p /docker-entrypoint-initdb.d && \
    echo "CREATE EXTENSION pgml;CREATE EXTENSION vector;" > /docker-entrypoint-initdb.d/setup.sql && \
    chmod 755 /docker-entrypoint-initdb.d/setup.sql

CMD ["postgres", "-c", "shared_preload_libraries=pgml"]
```

**Comment by zebehringer** [comment]
I mistook your intention. It isn't based on a cuda image, that's for sure. But yes, it is anything but lightweight as far as image size goes
