### ISSUE TITLE
XGBoost rust implementation seems broken

### ISSUE THREAD

**Issue by gaspardc-met** [postgresml/postgresml#1642]
- Running the examples notebooks
- Running with custom data
- XGBoost (rust implementation) has negative R2 score value for regression and classification tasks
- I tried changing the hyper-parameters (especially n_estimators) to no avail

Here with the example diabetes regression:
![image](https://github.com/user-attachments/assets/43d4a4e8-a436-4bd7-9fe0-d73d7f771585)

it's the worst classifier (by far) in the cancer detection: 
![image](https://github.com/user-attachments/assets/1b72196e-993d-42a0-ae54-a5948837d1a4)

Again it's worst by far on some powerplant data from Kaggle
![image](https://github.com/user-attachments/assets/bf37c8f9-3a85-411c-ac94-084a8f0786c8)

Note that it's not the case with the XGBoost/Random Forest from scikit-learn. 

It feels like something is wrong with the rust implementation

**Comment by montanalow** [comment]
This is a dup of #1622 which is fixed in master.

**Comment by gaspardc-met** [comment]
@montanalow : this was pulled from main/master 2 days ago
