### ISSUE TITLE
how I can set some filters on the dataset table to use for training

### ISSUE THREAD

**Issue by Bilal-Yousaf** [postgresml/postgresml#283]
As we are using SQL tables to fetch data for training. Do we have support to use data stored in only last two days for training and ignore old data?
One way I could imagine doing this is using the view in SQL. But that would need some extra lines, if we have this support in train call that would be great.

**Comment by montanalow** [comment]
I think you're correct on both points. For now, the easiest way to do this is by creating a `VIEW` with the filters that you'd like to train with. First class support for better feature and data handling support is on our roadmap, although we haven't nailed down what the APIs will look like yet.

I think it's likely we'll have both a mix of additional arguments to `train` that enable things like normalizing/standardizing inputs (that will also be applied at predict), but potentially something like temporary VIEWS defined as part of the call to train as well when you need a more powerful descriptive capability than the built in options.

**Comment by montanalow** [comment]
Closing in favor of views
