### ISSUE TITLE
XGBoost & LightGBM on Apple M1 & M2

### ISSUE THREAD

**Issue by levkk** [postgresml/postgresml#364]
XGBoost and LightGBM won't compile / segfault on Apple M1s (and M2s) aarch64. The issue comes from `openmp` which appears to break and requires special workarounds which seem to be unreliable.

XGBoost issue: https://github.com/dmlc/xgboost/issues/7039

**Comment by montanalow** [comment]
It looks like xgboost expects libraries to be linked from places that brew doesn't install by default.

This fixed it on my mac, and allows building:
```
brew install openblas
sudo mkdir -p /usr/local/opt/openblas
sudo ln -s /opt/homebrew/Cellar/openblas/0.3.21/lib /usr/local/opt/openblas/lib

brew install libomp
sudo mkdir /usr/local/opt/libomp
sudo ln -s /opt/homebrew/Cellar/libomp/15.0.2/lib /usr/local/opt/libomp/lib

cd /usr/local/lib
sudo ln -s /opt/homebrew/opt/libomp/lib/libomp.dylib .
```

**Comment by levkk** [comment]
Did you try training something with XGBoost? I remember being able to build it at some point, but running segfaulted.

**Comment by montanalow** [comment]
Yep. Training and predictions work.
