### ISSUE TITLE
Handling categorical variables

### ISSUE THREAD

**Issue by xgnusr** [postgresml/postgresml#443]
SELECT * FROM pgml.train(
	'pk20102022', 
	'classification', 
	'viewdata', 
	'inferencia', 
	'xgboost');

INFO:  Snapshotting table "viewdata", this may take a little while...
ERROR:  unhandled type: `text` for `inferencia`
CONTEXT:  src/orm/snapshot.rs:288:25
SQL state: XX000

'inferencia' can be: reliable, neutral or possible

any ideas ?

TNX !!

**Comment by levkk** [comment]
A quick fix could be to use a Postgres query to create categorical variables:

```sql
SELECT inferencia, row_number() OVER (ORDER BY 1) AS "class" FROM (SELECT DISTINCT(inferencia) FROM viewdata)
```

and then pass it to LightGBM as a categorical variable using hyperparameters:

```
hyperparams => '{"categorical_feature": <column position> }'
```

[LightGBM docs](https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature)

We will implement automatic handling of categorical variables in the new future, so hopefully this workaround works for you for now.

**Comment by montanalow** [comment]
Categoricals can now be handled generically with the preprocessing argument to train after #470. Documentation is [here](https://postgresml.org/user_guides/training/preprocessing/).
