### ISSUE TITLE
Unable to create new project 

### ISSUE THREAD

**Issue by nidhin077** [postgresml/postgresml#444]
I encountered an error "TypeError at /api/tables/columns/" while setting up a new project. I've included the entire screenshot of the error. kindly have a look.

![image](https://user-images.githubusercontent.com/107123789/197139123-342c2e89-b47d-4a48-8a2c-8ec5986f44d1.png)

I connected the pgml dashboard to my local Postgres database, I have made changes in allowed hosts entry in the following files which are under the directory pgml_dashboard .env, and settings.py 

kindly inform me of the best way to handle this error.

**Comment by montanalow** [comment]
Which version of the pgml extension do you have installed? You can check with 

```
 psql postgres://postgres@127.0.0.1:5433/pgml_development -c "select * from pgml.version();"
```

The dashboard in master expects extension version 2.0. You can also checkout a 1.0 tag from github if you'd like to work with an old version of the dashboard and extension.  Upgrading an existing 1.0 installation to 2.0 is [covered here](https://postgresml.org/user_guides/setup/v2/upgrade-from-v1/), if that turns out to be the issue.

**Comment by nidhin077** [comment]
@montanalow I have upgraded the postgresml to 2.1.0. However, the issue is still there.  Could you please check the same?

![image](https://user-images.githubusercontent.com/107123789/198568433-cb08ea14-ba35-436e-a03d-e5a6f6c67efa.png)

**Comment by montanalow** [comment]
Where you able to run the 1.0 to 2.0 migration script?

https://postgresml.org/user_guides/setup/v2/upgrade-from-v1/

**Comment by nidhin077** [comment]
@montanalow Actually, I had just set up a fresh instance of PostgreSQL and linked the dashboard to the database. After that, I encountered the above described issue while attempting to create a new project.

**Comment by montanalow** [comment]
I see the issue now. This is a bug in the new project wizard related to tables in the public schema. We'll need a patch to get this sorted. In the mean time a fix has already been applied to the command line version of project creation with [`pgml.train()`](https://postgresml.org/user_guides/training/overview/).

**Comment by nidhin077** [comment]
@montanalow Once the bug has been sorted. Please update here.

**Comment by montanalow** [comment]
The new project wizard has been removed until we can design it to cover more use cases, in favor of a direct SQL workflow that utilizes the APIs, which is supported via the console and notebooks (as well as standalone SQL clients).
