### ISSUE TITLE
unable to locate postgresml-13

### ISSUE THREAD

**Issue by nidhin077** [postgresml/postgresml#460]
When I'm running apt-get update && apt-get install -y postgresql-pgml-13, I'm getting error E: Unable to locate package postgresql-pgml-13

Could you please have a check on this.

**Comment by levkk** [comment]
What's your Ubuntu version? I'll build a package for it for you.

**Comment by nidhin077** [comment]
using the ubuntu 22.04 version, Also, please let me know how to build the same.

**Comment by levkk** [comment]
```
apt search postgresql-pgml-13

Sorting... Done
Full Text Search... Done
postgresql-pgml-13/unknown 2.1.0 amd64
  PostgresML - machine learning with PostgreSQL
```

Done, should be good to go.

To build one yourself, use our build script [here](https://github.com/postgresml/postgresml/tree/master/pgml-extension#packaging).

**Comment by nidhin077** [comment]
Thanks, Can you create a package for Debian.

**Comment by nidhin077** [comment]
@levkk , I have installed the Postgresml on ubuntu, but while trying to add postgresml extension to the database it getting an error 

ERROR:  The xgboost package is missing. Install it with `sudo pip3 install xgboost`
ImportError: /usr/local/lib/python3.10/dist-packages/scipy/sparse/linalg/_isolve/../../../../scipy.libs/libopenblasp-r0-41284840.3.18.so: cannot read file data
CONTEXT:  src/api.rs:25:21


The xgboot has already been installed.  Please have a check on this.

**Comment by montanalow** [comment]
Looks like you're missing the open blas lib that scipy depends on. You can install it on Ubuntu with:
```
sudo apt-get install libopenblas-dev
```

**Comment by levkk** [comment]
SciPy ships with its own libopenblas. Looks like your SciPy installation is broken, maybe try reinstalling it with pip. It also looks like your Python installation is in a different place from normal system Python3. Since you're on Ubuntu 22.04, you should have Python 3.10 installed already in `/usr/lib/python3`.

**Comment by nidhin077** [comment]
@montanalow @levkk Thanks for the update, I will check the same.

Could please create a package for debian.
