### ISSUE TITLE
what is happening ?

### ISSUE THREAD

**Issue by xgnusr** [postgresml/postgresml#473]
SELECT 'id_inferencia', pgml.predict( 2, ARRAY [ 1.84,0.05565,133,133,16739,1.38,0.006346 ]) AS prediccion;
->
Column text   | prediccion real
id_inferencia  |  1

SELECT 'id_inferencia', pgml.predict( 2, ARRAY[ 'var0', 'var1', 'var2', 'var3', 'var4', 'var5', 'var6' ]) AS prediccion
FROM pgml.vwdata;

ERROR: function pgml.predict(integer, text[]) does not exist
LINE 1: SELECT id_inferencia, pgml.predict( 2, ARRAY[ 'var0', 'var1'...
                               ^
HINT: No function matches on the name and types of arguments. It may be necessary to add explicit type casting.
SQL state: 42883
Character: 23

I'm a bit lost ...

TNX !!

**Comment by montanalow** [comment]
If `'var0'` is meant to refer to a column in pgml.vwdata, you'll need to use double quotes (or none) rather than single quotes which denotes a `TEXT` string.

**Comment by xgnusr** [comment]
Same behavior...

SELECT "id_inferencia", pgml.predict( 2, ARRAY[ "var0", "var1", "var2", "var3", "var4", "var5", "var6" ]) AS prediccion
FROM pgml.vwdata;


ERROR:  no existe la función pgml.predict(integer, double precision[])
LINE 1: SELECT "id_inferencia", pgml.predict( 2, ARRAY[ "var0", "var...
                                ^
HINT:  Ninguna función coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversión explícita de tipos.
SQL state: 42883
Character: 25


SELECT id_inferencia, pgml.predict( 2, ARRAY[var0, var1, var2, var3, var4, var5, var6]) AS prediccion
FROM pgml.vwdata;



ERROR:  no existe la función pgml.predict(integer, double precision[])
LINE 1: SELECT id_inferencia, pgml.predict( 2, ARRAY[ var0, var1, va...
                              ^
HINT:  Ninguna función coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversión explícita de tipos.
SQL state: 42883
Character: 23

**Comment by montanalow** [comment]
The predict function only accepts `FLOAT4[]` feature arrays. You'll need to downcast your double precision array as you pass it to the function.

```
SELECT "id_inferencia", pgml.predict( 2, ARRAY[ "var0", "var1", "var2", "var3", "var4", "var5", "var6" ]::FLOAT4[]) AS prediccion
FROM pgml.vwdata;
```

**Comment by xgnusr** [comment]
Great, now it works perfectly!!

TNX !!
