### ISSUE TITLE
signal 11: Segmentation fault

### ISSUE THREAD

**Issue by dusanmarjanovic** [postgresml/postgresml#530]
I've pulled fresh version of postgresml from github instead of using ubuntu package (as from what I saw it still doesn't have preprocessing features) and managed to compile it and update .so library with the new one. But now it gives me a segfault even on the basic example:

  2023-02-03 16:34:32.815 UTC [125591] LOG:  database system is ready to accept connections
  2023-02-03 16:34:44.698 UTC [125591] LOG:  server process (PID 125611) was terminated by signal 11: Segmentation fault
  2023-02-03 16:34:44.698 UTC [125591] DETAIL:  Failed process was running: SELECT * FROM pgml.train(
            project_name => 'Breast Cancer Detection',
            task => 'classification',
            relation_name => 'pgml.breast_cancer',
            y_column_name => 'malignant'
          )

ubuntu 22.04, postgresql 14

**Comment by montanalow** [comment]
I'm guessing you can successfully run tests locally on your build with `cargo pgx test`? Did you build w/ `cargo pgx package`? This sounds like there may be some incompatibility between different parts of the installation, maybe something is leftover from the previous `create extension ...` call? Have you tried doing a `cargo pgx install` (which depends on `pg_config` being setup with the correct paths)?

Can you add the exact steps you went through to upgrade the .so?

PS. We're planning to cut a new release with preprocessing next week.

**Comment by dusanmarjanovic** [comment]
all tests run successfully:
test result: ok. 47 passed; 0 failed; 0 ignored; 0 measured; 0 filtered
out; finished in 279.30s

Yes, built with cargo pgx package.
For the steps, I just followed the exact instructions on building from
source and just copied the compiled .so instead of the one that came from
the .deb package.

Tried now with cargo pgx install also, it was done successfully but still
the same seg fault. If there's anything else I can provide please let me
know, otherwise I'll have to wait for the prepared package.

**Comment by montanalow** [comment]
This is interesting. I can't repro any segfaults on my setup, but I can get one on our build machine during `cargo pgx package`. It's coming from the installation process during pgx macros generating function signatures. Why this works on some machines and not others is not obvious to me. I'm going to work on a patch for the build process, including updating pgx, before doing an actually release (that includes preprocessing).

**Comment by dusanmarjanovic** [comment]
Thanks, if you need me to test that patch before releasing let me know, also this is my test vm running nothing but pgml so I can give you access if you need it for some testing etc.

**Comment by montanalow** [comment]
I’d love to know if this patch fixes it for you. It’s a shot in the dark.

**Comment by dusanmarjanovic** [comment]
hi, any progress on this? thanks

**Comment by montanalow** [comment]
@dusanmarjanovic were you able to test a new build w/ #533?

**Comment by dusanmarjanovic** [comment]
sorry for late reply @montanalow, i did try and it was the same, but installed from the apt and its working fine
