### ISSUE TITLE
failed to find image postgresml-postgres

### ISSUE THREAD

**Issue by njwgroeneveld** [postgresml/postgresml#565]
Hi all,

I'm trying to install postgresML in a docker container via the following guide:
https://postgresml.org/user_guides/setup/quick_start_with_docker/
Unfortunately, its steps out with the following error in the Running step:
Error response from daemon: failed to find image postgresml-postgres: docker.io/library/postgresml-postgres: No such image

Anyone know how to proceed with this?

Tnx in advance,

Niels

**Comment by montanalow** [comment]
Hi,

I'm able to run `docker-compose up` successfully, from a fresh start after running `docker system prune -all` to make sure I don't have something cached that is making this work. Was this a transient network issue? Docker has also been [removing open source images](https://blog.alexellis.io/docker-is-deleting-open-source-images/), so I wanted to make sure that report is unrelated to your issue.

**Comment by njwgroeneveld** [comment]
Also when I first do the `podman system prune` command before the  `docker-compose up.`  Its still showing the error which I mentioned above. I do see that a container is started at the end, but based on that error it doesn't feel complete.

**Comment by montanalow** [comment]
I'm not familiar with podman, but `docker.io/library/postgresml-postgres` is not something we've created or listed in any of our docker setup scripts. Have you setup some local docker registry or additional configuration?

**Comment by montanalow** [comment]
Closing due to staleness.
