### ISSUE TITLE
Catboost integration

### ISSUE THREAD

**Issue by Slach** [postgresml/postgresml#570]
Look to https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper, could it be integrated to postgresml?

**Comment by montanalow** [comment]
Yes, we could use [bindgen](https://github.com/rust-lang/rust-bindgen) to create a rust interface, and it looks like it would follow the integration pattern used for [xgboost](https://github.com/postgresml/postgresml/blob/master/pgml-extension/src/bindings/xgboost.rs) and [lightgbm](https://github.com/postgresml/postgresml/blob/master/pgml-extension/src/bindings/lightgbm.rs) fairly closely.

**Comment by montanalow** [comment]
It looks like catboost already has [rust bindings](https://github.com/catboost/catboost/tree/master/catboost/rust-package)
