### ISSUE TITLE
Broken link ( https://postgresml.org/projects/ ) in Tutorial 1: ⏱️ Real Time Fraud Detection 

### ISSUE THREAD

**Issue by data-envoy** [postgresml/postgresml#582]
Hi, I'm following the tutorials, and they are super helpful.

IDK if this is exactly the right place to report.

On [Tutorial 1: ⏱️ Real Time Fraud Detection](https://postgresml.org/dashboard/notebooks/2) , step 7, there is a broken link.

> We'll organize our work on this task under the project name "Breast Cancer Detection", which you can now see it in your [list of projects](https://postgresml.org/projects/).

And

> You can pop over to the [projects](https://postgresml.org/projects/) tab for a visualization

Edit: the broken links are through multiple tutorials, and I realise now the links should point to https://postgresml.org/dashboard/projects

**Comment by data-envoy** [comment]
No problem.

**Comment by montanalow** [comment]
Fixed by removing the non dynamic links in question.
