### ISSUE TITLE
Unable to use Categorical columns as target or input fields for classification and regression

### ISSUE THREAD

**Issue by EVAUTOAI** [postgresml/postgresml#595]
For classification, if the target is categorical the model is not getting trained and is throwing assertion error. It expects the categories to be numbers such as 0, 1, 2, etc.
For regression, the model is getting trained with categorical input fields but when predicting it is not accepting categorical values.
How to incorporate categorical columns with string values as input or target?

**Comment by montanalow** [comment]
There are a few examples for handling categorical data in the docs. It's important to note the different call to predict with categorical data takes a `row` that may include strings etc, rather than an `array` of pure floats. i.e. you'll need to use the row syntax for that features `('a','b','c')` instead of the array syntax `ARRAY['a','b','c']`.

https://postgresml.org/docs/guides/training/preprocessing

**Comment by EVAUTOAI** [comment]
The preprocessing command is not allowed in pgml version 2.4.0. Is there an alternative for that version?

**Comment by montanalow** [comment]
I'd recommend upgrading to 2.4.4 for bug fix reasons w/ 'alter extension pgml update' after installing the latest version. Particulately if you've been using a pre 2.4 version. 

If you'd like more help debugging a full sql statement and error message would be helpful.

**Comment by EVAUTOAI** [comment]
Upgraded to the latest version. Even now there seems to be a problem.

I have a simple iris dataset where the "Class" field has categorical values.
Sample:
 Sepallength |    Class    | Sepalwidth | Petallength | Petalwidth 
-------------+-------------+------------+-------------+------------
         5.1 | Iris-setosa |        3.5 |         1.4 |        0.2
         4.9 | Iris-setosa |          3 |         1.4 |        0.2
         4.7 | Iris-setosa |        3.2 |         1.3 |        0.2
         4.6 | Iris-setosa |        3.1 |         1.5 |        0.2
           5 | Iris-setosa |        3.6 |         1.4 |        0.2

The command I tried to run as per documentation
SELECT pgml.train(
    project_name => 'preprocessed_model', 
    task => 'classification', 
    relation_name => 'iris',
    target => 'Class', 
    preprocess => '{
        "Class":   {"encode": "target"}
    }'
);


ERROR:  function pgml.train(project_name => unknown, task => unknown, relation_name => unknown, target => unknown, preprocess => unknown) does not exist
LINE 1: SELECT pgml.train(
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by montanalow** [comment]
We've updated the serverless cloud dependencies to a version that includes the preprocessing functionality. Thanks for the report!
