### ISSUE TITLE
Streaming responses from LLMs

### ISSUE THREAD

**Issue by montanalow** [postgresml/postgresml#601]
It'd be nice to have an API over a server side cursor that returned individual tokens as rows from the model to stream responses back to the end user.

**Comment by aplchian** [comment]
ye

**Comment by ishaan-jaff** [comment]
Hi @montanalow @aplchian  I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
You can use our proxy server or spin up your own proxy server using LiteLLM**

## Usage
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# falcon call
response = completion(model="falcon-40b", messages=messages)
```

**Comment by montanalow** [comment]
Completed by @SilasMarvin
