### ISSUE TITLE
pgml.embed does not work

### ISSUE THREAD

**Issue by dkoding** [postgresml/postgresml#602]
I use the hosted version of PGML. 

select pgml.version() returns 2.1.1.

As a test, I have a database 

```
create table european_anthems (
    country varchar(20),
    anthem_first_line varchar(255)
);
```

I have inserted 20 lines into this table OK and can query them as normal.

I now want to create embedding vectors for anthem_first_line, and according to the manual this can be done using:

```
SELECT pgml.embed('distilbert-base-uncased', anthem_first_line)
FROM european_anthems;
```

However this gives the error message

`[42883] ERROR: function pgml.embed(unknown, character varying) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 8`

Has the method been changed? Do I need to enable something extra on the hosted version of PGML to make this work?

Can you please update the documentation accordingly?

**Comment by dkoding** [comment]
https://postgresml.org/dashboard/notebooks/11 demonstrates the issue

**Comment by levkk** [comment]
Just upgraded our free tier with more powerful hardware. You should be able to use embeddings now. Thank you for reporting this issue! I'll keep it open until you can confirm that embeddings are working for you.
