### ISSUE TITLE
Embedding vector search is performed on RAM?

### ISSUE THREAD

**Issue by hwasiti** [postgresml/postgresml#658]
Most vector database algorithms are carried out in RAM. Where are the PostgreSQL database embeddings stored? Should we expect them stored on disk like how ordinary postgresql databases file stored? Which means no large RAM is required for large embedding vectors dataset.

Almost all other vector databases are RAM and not disk based, so this will be nice if postgres stands out by operating like any sql database without huge RAM requirements.

How about pgvector?

**Comment by montanalow** [comment]
Postgres will effectively page portions of the IVFFLAT index between RAM and HDD as necessary, so you are correct that this is a nice scalability advantage pgvector has over some competitors, especially if some `lists` are hot, and others not. Of course if there is ample RAM in the system allocated to either Postgres `shared_buffers` or the operating system page cache to hold the entire index, then there will be no disk activity. 

It's worth noting that pgvector requires a modest amount of `maintenance_work_mem` while initially building the index, which is generally an offline process, and is only a fraction of the final index size. You'll get a helpful error message if you have not configured enough `maintenance_work_mem` to create the index in the beginning.
