### ISSUE TITLE
Python version support for 3.6

### ISSUE THREAD

**Issue by craigkerstiens** [postgresml/postgresml#69]
Hi,

Curious if the Python 3.7 is a hard requirement or if you could possibly run on some earlier 3.x version. In particular curious about Python 3.6 as we run with it already and would love to give this a try.

**Comment by montanalow** [comment]
After looking into this, Python 3.6 was End of Life on 23 Dec 2021. A few of our key dependencies have also dropped support for 3.6, primarily scikit-learn, so I think 3.7 will have to stay a hard requirement.
