### ISSUE TITLE
Improve Error Messaging/Validation for Non-Existent model_id in `generate_embeddings`

### ISSUE THREAD

**Issue by aplchian** [postgresml/postgresml#710]
**Problem:**

Invoking `generate_embeddings` with a non-existent `model_id` results in a non-specific `list index out of range` error.

**Reproduction:**

```python
collection.generate_embeddings(model_id=99999999, splitter_id=splitter_id)
```

<img width="594" alt="image" src="https://github.com/postgresml/postgresml/assets/7388748/df9fcee6-7ca5-4c51-bcce-d7f96e230ee5">

**Expected Behavior:**

Raise a more descriptive error, e.g., `Error: The provided model_id does not exist.` 

**Solution:**

Implement an extra check for `model_id` validity and provide a more informative error message.

**Comment by SilasMarvin** [comment]
Closing this as it is no longer an issue
