### ISSUE TITLE
Implement Validation for db.create_or_get_collection Input

### ISSUE THREAD

**Issue by aplchian** [postgresml/postgresml#711]
Issue: 
Currently the SDK throws syntax errors when db.create_or_get_collection function receives an invalid `collection_name` parameter. For instance, passing in `mobile-vikings` as the collection name results in errors related to incorrect syntax near "-".
<img width="729" alt="image" src="https://github.com/postgresml/postgresml/assets/7388748/dea381e9-3c89-448c-9af0-3ed5c6392def">

Proposed Solution: 
Introduce input validation for `collection_name` to prevent syntax errors.

**Comment by montanalow** [comment]
The SDK should be quoting these identifiers to prevent issues like this.

**Comment by jsaied99** [comment]
We should execute any SQL statement using parameters as defined [PEP-249](http://www.python.org/dev/peps/pep-0249/)](https://peps.python.org/pep-0249/#id20). 
We should replace it using the specification.
 
`run_create_or_insert_statement_params(conn, "INSERT INTO pgml.collections (name) VALUES (%(name)s)", {"name": name})`

I can create a PR for this. We should ideally change it for **every** SQL statement, not just inserts.

**Comment by montanalow** [comment]
@jsaied99 @santiatpml has started moving all the queries to a builder in #705, which should help with these sorts of issues.

**Comment by SilasMarvin** [comment]
Closing this as it is no longer an issue
