### ISSUE TITLE
any plans to add support for llama.cpp?

### ISSUE THREAD

**Issue by daboe01** [postgresml/postgresml#717]
this would enable to leverage large language models.

**Comment by daboe01** [comment]
this would enable to use instruction tuned large language models that otherwise require expensive graphics cards.

**Comment by levkk** [comment]
LLama has a quantized version that we could implement using GGML (https://github.com/rustformers/llm).

**Comment by daboe01** [comment]
@levkk yes, that is why i suggested to support llama.cpp. to get acceptable performance for cpu-only servers using llm.

**Comment by levkk** [comment]
I think that would be a great addition. If you have time to play around with GGML and the `llm` crate, we would absolutely welcome a PR/contribution there.

**Comment by daboe01** [comment]
one option could be to keep the api from python transformers and use rustformers/llm whenever the specified HF-model is GGML.

**Comment by daboe01** [comment]
as for integrating you could go the python way:
https://github.com/abetlen/llama-cpp-python
