### ISSUE TITLE
Connection getting dropped after error thrown

### ISSUE THREAD

**Issue by aplchian** [postgresml/postgresml#736]
It looks like there is an issue with the db connection after an error is thrown. In the screenshot below I get a `list index out of range error`, and then on subsequent requests i get the `couldn't get a connection after 30.0 sec`

<img width="1144" alt="image" src="https://github.com/postgresml/postgresml/assets/7388748/d4591dc5-1bf7-438c-9fa5-845c526eae15">

**Comment by SilasMarvin** [comment]
Closing this as it is no longer an issue
