### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by danieljose** [postgresml/postgresml#741]
Hello.
I'm trying a new install and it fails. I'm using the docker installation.
This works: git clone https://github.com/postgresml/postgresml
This fails:
cd postgresml && docker-compose up

 => ERROR [ 6/15] RUN apt-get update && apt-get install -y postgresql-pgml-14=2.5.2                                3.8s
------
 > [ 6/15] RUN apt-get update && apt-get install -y postgresql-pgml-14=2.5.2:
#0 0.418 Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
#0 0.490 Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
#0 0.568 Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
#0 1.463 Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
#0 1.501 Hit:5 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
#0 1.623 Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
#0 2.159 Ign:7 https://apt.postgresml.org jammy InRelease
#0 2.415 Get:8 https://apt.postgresml.org jammy Release [2359 B]
#0 2.614 Ign:9 https://apt.postgresml.org jammy Release.gpg
#0 2.835 Get:10 https://apt.postgresml.org jammy/main amd64 Packages [1656 B]
#0 2.842 Fetched 4015 B in 3s (1588 B/s)
#0 2.842 Reading package lists...
#0 3.276 Reading package lists...
#0 3.681 Building dependency tree...
#0 3.761 Reading state information...
#0 3.763 Package postgresql-pgml-14 is not available, but is referred to by another package.
#0 3.763 This may mean that the package is missing, has been obsoleted, or
#0 3.763 is only available from another source
#0 3.763
#0 3.764 E: Version '2.5.2' for 'postgresql-pgml-14' was not found
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y postgresql-pgml-14=${PGML_VERSION}]: exit code: 100

Thanks

**Comment by levkk** [comment]
#742 I thought we saved previous versions of the package in our deb repo, surprised that we're not. Sorry about that.
