### ISSUE TITLE
Permissions error with pgml.embed

### ISSUE THREAD

**Issue by agapebondservant** [postgresml/postgresml#749]
Getting the following error when I run this query

```
SELECT pgml.version() /* returns 2.5.3 */
SELECT pgml.load_dataset('tweet_eval', 'sentiment'); /* runs with no issues */
SELECT text, pgml.embed('distilbert-base-uncased', text)
FROM pgml.tweet_eval
LIMIT 10;
```

I get
`SQL Error [XX000]: ERROR: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'PermissionError'>, value: PermissionError(13, 'Permission denied'), traceback: Some(<traceback object at 0x7f6c962a0c80>) }`

(Running as superuser)

Can anyone advise? Thanks!

**Comment by montanalow** [comment]
Resolved on Discord: https://discord.com/channels/1013868243036930099/1120302118230818889

**Comment by montanalow** [comment]
Resolved on Discord: https://discord.com/channels/1013868243036930099/1120302118230818889
