### ISSUE TITLE
provided pgml.control doesn't work for postgres 12, although pgml listed compatible with pg 11 through 15

### ISSUE THREAD

**Issue by LrWm3** [postgresml/postgresml#769]
When I attempted to install pgml.control into postgres 12 & load the extension [by following this documentation](https://postgresml.org/docs/guides/setup/v2/installation), I saw an error that indicated it was failing to load the extension due to 'unrecognized parameter "trusted"' in the pgml.control file. 

I was able to get past this issue by removing this line from the pgml.control file. Afterwards, I could load and use the extension in pg12.

pgml.control edited
```
comment = 'pgml:  Created by the PostgresML team'
default_version = '2.5.3'
module_pathname = '$libdir/pgml'
relocatable = false
superuser = true
schema = 'pgml'

```
I believe this is because the 'trusted' parameter for extension control files was not added until postgres 13 onwards.

full log line below, before i removed the 'trusted' parameter as shown above from pgml.control.

have a good one :+1: 

`````
postgres-multimodal-postgres-multimodal-1  |    CREATE EXTENSION IF NOT EXISTS pgml
postgres-multimodal-liquibase-1            | 
postgres-multimodal-liquibase-1            | Unexpected error running Liquibase: Migration failed for changeset sql/00010_initial_database_setup.sql::raw::includeAll:
postgres-multimodal-liquibase-1            |      Reason: liquibase.exception.DatabaseException: ERROR: unrecognized parameter "trusted" in file "/usr/share/postgresql/12/extension/pgml.control" [Failed SQL: (0) ----------------
`

**Comment by montanalow** [comment]
@levkk I believe this is fixed
