### ISSUE TITLE
auto_gptq usage

### ISSUE THREAD

**Issue by danieljose** [postgresml/postgresml#783]
Hello.
I  try one of your examples and it fails:

```
SELECT pgml.transform(
    task => '{
      "task": "text-generation",
      "model": "mlabonne/gpt2-GPTQ-4bit"
    }'::JSONB,
    inputs => ARRAY[
        'Once upon a time,'
    ],
    args => '{"max_new_tokens": 32}'::JSONB
);
```
ERROR:  Traceback (most recent call last):
  File "", line 139, in transform
  File "", line 87, in __init__
 ModuleNotFoundError: No module named 'auto_gptq' 

SQL state: XX000

I have installed auto_gptq with pip with success. I'm using wsl 2.
I open python and I can import auto_gptq.
Thanks

**Comment by montanalow** [comment]
Are you using any virtual envs? Postgres uses system Python by default, which requires `sudo pip install ...`.

**Comment by danieljose** [comment]
Sorry, yes, I was inside a venv :-) Thanks.
