### ISSUE TITLE
model Salesforce/xgen-7b-8k-inst

### ISSUE THREAD

**Issue by danieljose** [postgresml/postgresml#797]
Hello. I'm trying to use the new model of Salesforce
Salesforce/xgen-7b-8k-inst

```
SELECT pgml.transform(
    task => '{
      "task": "text-generation",
      "model": "Salesforce/xgen-7b-8k-inst"
    }'::JSONB,
    inputs => ARRAY[
        'Once upon a time,'
    ],
    args => '{"max_new_tokens": 32}'::JSONB
);

```

it gives the error:

```
ERROR:  Traceback (most recent call last):
  File "", line 141, in transform
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 885, in pipeline
    tokenizer = AutoTokenizer.from_pretrained(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
 ValueError: Tokenizer class XgenTokenizer does not exist or is not currently imported. 

SQL state: XX000

```

The XgenTokenizer is in the repository:
https://huggingface.co/Salesforce/xgen-7b-8k-base/blob/main/tokenization_xgen.py
Is possible to import somehow this .py file to solve the error?
Thanks

**Comment by montanalow** [comment]
Looks like this model needs an additional dependency from https://huggingface.co/Salesforce/xgen-7b-8k-base:

```
pip install tiktoken
```

Maybe we should add this to the requirements.txt.

**Comment by danieljose** [comment]
Yes, I had already installed tiktoken before sending the error here, so the problem seems to be centered on the inability to load the XgenTokenizer class. Is there a way to do it?

**Comment by montanalow** [comment]
Looks like they are using [some config](https://huggingface.co/Salesforce/xgen-7b-8k-base/blob/main/tokenizer_config.json) to replace the standard AutoTokenizer, although I'm not sure how that config is typically executed by HF.  The example in the model card seems like it should "just work" like all the other auto_tokenizers, but there may be some missing additional permissions or config for PostgresML.

**Comment by danieljose** [comment]
I made it work! Adding "trust_remote_code": true

```
SELECT pgml.transform(
    task => '{
      "task": "text-generation",
      "model": "Salesforce/xgen-7b-8k-inst",
	"trust_remote_code": true
    }'::JSONB,
    inputs => ARRAY[
        'Once upon a time,'
    ],
    args => '{"max_new_tokens": 32}'::JSONB
);

```
