### ISSUE TITLE
ERROR:  syntax error at or near "NULL"

### ISSUE THREAD

**Issue by dventimihasura** [postgresml/postgresml#815]
Hello!

When following the [Quick Start w/ Docker](https://postgresml.org/docs/guides/setup/quick_start_with_docker) guide, I get the following error on start-up with Docker Compose:

```sh
ERROR:  syntax error at or near "NULL"
```

I suspect this is due to a syntax error in the regression testing code:

https://github.com/postgresml/postgresml/blob/8bbc08ffdfa8ae287d62c0b2007f4c11f10e5f8d/pgml-extension/src/orm/task.rs#L84

This line in `task.rs` is written:

```rust
"ORDER BY models.metrics->>'{}' {} NULL LAST",
```

If this is for PostgreSQL, I think this is the wrong syntax.  I think in PostgreSQL an `ORDER BY` clause should have the keywords `NULLS LAST` not `NULL LAST`.  The PostgreSQL docs seem to support this:

https://www.postgresql.org/docs/current/sql-select.html

I could be wrong, though.  Thanks!
Best,
David

**Comment by montanalow** [comment]
You are correct, this is a regression. I'll work on a patch for later today, unless you want the honors. I think we need to figure out why this wasn't caught by our test suite.
