### ISSUE TITLE
pgml.embed as a function

### ISSUE THREAD

**Issue by zzart** [postgresml/postgresml#818]
First of all this is an awesome project! Many thanks for your hard work. 
I've stumbled across one issue I cannot comprehend. 

So I've have a query for embeds
```sql
WITH query AS (
    SELECT pgml.embed('intfloat/e5-small-v2', 'foo bar?')::vector AS embedding
)
SELECT kb, tag
FROM cm_embeddings,
     query
ORDER BY cm_embeddings.embedding <-> query.embedding
LIMIT 10;
```
This query executes in around 1sec. 
If I wrap it in a function and call it, it takes 2min to execute :( 
This is on 200 rows of data. 

```sql
create or replace function query_embedding(phase varchar)
    returns TABLE
            (
                kb    varchar,
                model varchar
            )
as
$$
with query AS (
    SELECT pgml.embed('intfloat/e5-small-v2', phase)::vector AS embedding
)
SELECT kb, tag
FROM cm_embeddings,
     query
ORDER BY cm_embeddings.embedding <-> query.embedding
LIMIT 10
$$
    LANGUAGE SQL;

SELECT query_embedding('foo bar');
```

Is it recreating embedding for each row ?? 
In my case `phase` parameter has to be dynamic so I have to use make it somehow into a function I can expose  to internal API. 
Is there any other way I should be tackling this ?

**Comment by zzart** [comment]
I discovered that it's to do with using both CTE and dynamic parameter. 
If I'm using CTE with hardcoded `phase` value it works as expected. 
If I don't use CTE and have dynamic `phase` it also works as expected. 
It would still be nice to use CTE as it's much cleaner.

**Comment by montanalow** [comment]
I think you can move the query.embedding into a subselect rather than a join to avoid re-computation for each row in the table. e.g.

```
WITH query AS (
    SELECT pgml.embed('intfloat/e5-small-v2', phrase)::vector AS embedding
)
SELECT kb, tag
FROM cm_embeddings
ORDER BY cm_embeddings.embedding <-> (SELECT query.embedding FROM query)
LIMIT 10;
```

**Comment by zzart** [comment]
Thanks @montanalow that did the trick. I was slowly converging on the same solution ;) I appreciate your time!
