### ISSUE TITLE
ModuleNotFoundError("No module named 'packaging'")

### ISSUE THREAD

**Issue by avinashkurup** [postgresml/postgresml#844]
Hi,

I need to use the embed functionality in pgml 2.6+ in PostgreSQL-14, I [built from sources for Linux](https://postgresml.org/docs/guides/setup/v2/installation) the pgml extension on my ubuntu 20.04 system since the latest version supported in apt repository is pgml 2.1.1. I now face the error: 

SQL Error [XX000]: ERROR: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'packaging'"), traceback: Some(<traceback object at 0x7fa360cba280>) }

I installed the requirement.txt but find the 'packaging' python package missing in it, I installed it in the environment postgresql uses but still face this error.

Please tell me what I'm missing here.

Thank you.

[packaging-error-pgml.txt](https://github.com/postgresml/postgresml/files/12108427/packaging-error-pgml.txt)

**Comment by levkk** [comment]
Hi there. Have you tried installing `packaging` with pip to see if fixes the issue?

**Comment by montanalow** [comment]
`pip install -r requirements.txt` resolves the following, which includes `packaging`. Are you installing and activating the correct virtual or system env?

```
Installing collected packages: tokenizers, sentencepiece, safetensors, pytz, py-cpuinfo, ninja, mpmath, lit, InstructorEmbedding, hjson, cmake, xxhash, tzdata, typing-extensions, tqdm, threadpoolctl, tenacity, tabulate, sympy, rouge, regex, python-dateutil, pygments, psutil, portalocker, pillow, packaging, orjson, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, numpy, networkx, mypy-extensions, multidict, mdurl, MarkupSafe, lxml, joblib, greenlet, fsspec, frozenlist, filelock, einops, dill, colorama, click, charset-normalizer, async-timeout, yarl, typing-inspect, SQLAlchemy, scipy, sacremoses, sacrebleu, pydantic, pyarrow, pandas, nvidia-cusolver-cu11, nvidia-cudnn-cu11, numexpr, nltk, multiprocess, marshmallow, markdown-it-py, jinja2, huggingface-hub, aiosignal, xgboost, transformers, scikit-learn, rich, openapi-schema-pydantic, lightgbm, langsmith, dataclasses-json, ctransformers, aiohttp, langchain, datasets, triton, torch, accelerate, torchvision, peft, torchaudio, sentence-transformers, deepspeed, auto-gptq
```

**Comment by avinashkurup** [comment]
> Hi there. Have you tried installing `packaging` with pip to see if fixes the issue?

I had to run these commands manually to fix the issue.

pip uninstall packaging
pip install packaging
     
pip uninstall python-dateutil
pip install python-dateutil
     
pip uninstall six
pip install six
     
pip uninstall psutil
pip install psutil
     
pip uninstall pygments
pip install pygments
     
sudo systemctl restart postgresql

**Comment by avinashkurup** [comment]
> 

Yes I am, Im not using virtualenv but installing the packages in the system env.

**Comment by montanalow** [comment]
Thanks for reporting back on the fix! I've updated requirements.txt today with the latest versions of packages to help resolve in the future.
