### ISSUE TITLE
Fix upsert method on sdk

### ISSUE THREAD

**Issue by aplchian** [postgresml/postgresml#893]
A few weeks ago @SilasMarvin mentioned that there may be a bug with the upsert method in the SDK. I believe the intended functionality for that method is to upsert based on the document ID. Then, after overwriting older documents and running the "generate embeddings" function, it should also overwrite the old embeddings. However, I think it currently doesn't overwrite the old chunks or embeddings. Would be really nice if this was fixed 🙏

**Comment by SilasMarvin** [comment]
Thank you for creating an issue for this. We have been discussing our plans to fix this, and the patch is coming out in the next SDK version! Hold tight and I'll update progress here when it is out.

**Comment by SilasMarvin** [comment]
Fixed with SDK version 0.9.0
