### ISSUE TITLE
Iris models always predict the same class

### ISSUE THREAD

**Issue by samdobson** [postgresml/postgresml#91]
Following the [iris classification example](https://github.com/postgresml/postgresml/blob/v0.7.0-pypi/pgml-extension/examples/classification.sql), you end up with a model that classifies every flower as `Iris-virginica`.

```
pgml_development=# SELECT pgml.predict('Iris Classifier', ARRAY[sepal_length, sepal_width, petal_length, petal_width]) AS prediction, count(target) FROM pgml.iris GROUP BY prediction;
 prediction | count
------------+-------
          2 |   150
(1 row)
```

This is the case for at least the following algorithms:

* linear
* ridge
* xgboost
* random_forest

**Comment by montanalow** [comment]
New version 0.8.0 is being released with a fix.

**Comment by montanalow** [comment]
New release: https://github.com/postgresml/postgresml/releases/tag/v0.8.0
