### ISSUE TITLE
Switch to unix line endings?

### ISSUE THREAD

**Issue by samdobson** [postgresml/postgresml#96]
[GitHub recommends](https://help.github.com/articles/dealing-with-line-endings/) to always use `\n` as a newline character in git-handled repos.

Windows line endings make it difficult to collaborate with folks using unix, and result in the docker-compose entrypoint scripts being parsed incorrectly on linux:
```
postgresml-admin-1     | /app/docker/entrypoint.sh: line 8: $'\r': command not found
postgresml-admin-1     | /app/docker/entrypoint.sh: line 23: syntax error: unexpected end of file
```

This should be an [easy fix](https://stackoverflow.com/questions/1889559/git-diff-to-ignore-m/1889699#18896990). I haven't created a PR, because it would involve changing a large number of files...

**Comment by montanalow** [comment]
We'll add a linter to CI to catch this in the future. Thanks for the heads up!
